name: Deployment

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"

env:
  IMAGE: ${{github.repository_owner}}/android-build-tools
  REGISTRY: ghcr.io

jobs:
  getChangedImageTags:
    runs-on: ubuntu-latest
    outputs:
      changedImageTags: ${{steps.filter.outputs.filteredPaths}}

    steps:
      - uses: actions/checkout@v2

      - id: files
        name: Get changed files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "json"

      - id: filter
        name: Filter files
        uses: inserteffect/github-actions-filter-changed-file-paths@v1.0
        with:
          changedFiles: ${{steps.files.outputs.all}}
          depth: 1

  uploadPackage:
    needs: getChangedImageTags
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      max-parallel: 1
      matrix:
        changedImageTags: ${{fromJSON(needs.getChangedImageTags.outputs.changedImageTags)}}

    steps:
      - uses: actions/checkout@v2

      - id: tag
        name: Set tag
        run: |
          changed_tag=${{matrix.changedImageTags}}
          echo "##[set-output name=tag;]$(echo ${changed_tag})"
          echo "##[set-output name=full_path;]$(echo ${{env.REGISTRY}}/${{env.IMAGE}}:$changed_tag)"

      - name: Build image
        run: |
          docker build \
          --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
          --build-arg VCS_REF=$(git rev-parse --short HEAD) \
          -t ${{steps.tag.outputs.full_path}} ./${{steps.tag.outputs.tag}}

      - name: Log in to registry
        run: echo "${{secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u ${{github.actor}} --password-stdin

      - name: Push image
        run: |
          docker push ${{steps.tag.outputs.full_path}}
